src/main/java/org/desnapress/model/User.java
//	Desna Press	State Agency 2014
//	Licensed under the Apache License, Version 2.0 (the "License"); you may not 
//	use this file except in compliance with the License. You may obtain a copy 
//	of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required 
//	by applicable law or agreed to in writing, software distributed under the 
//	License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
//	OF ANY KIND, either express or implied. See the License for the specific 
//	language governing permissions and limitations under the License.

package org.desnapress.model;

public class User {
	
	private long ID;
	public long getID() {
		return ID;
	}
	public void setID(long iD) {
		ID = iD;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword_hash() {
		return password_hash;
	}
	public void setPassword_hash(String password_hash) {
		this.password_hash = password_hash;
	}
	private String username;
	private String password_hash;

}

src/main/java/org/desnapress/controller/UserController.java
//	Desna Press	State Agency 2014
//	Licensed under the Apache License, Version 2.0 (the "License"); you may not 
//	use this file except in compliance with the License. You may obtain a copy 
//	of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required 
//	by applicable law or agreed to in writing, software distributed under the 
//	License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
//	OF ANY KIND, either express or implied. See the License for the specific 
//	language governing permissions and limitations under the License.

package org.desnapress.controller;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.annotation.Resource;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import javax.sql.DataSource;

import org.desnapress.data.Password;
import org.desnapress.model.User;

@ManagedBean(name = "userController")
@SessionScoped
public class UserController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String password;
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	// getters and setters
	@Resource(lookup = "java:jboss/datasources/mysql")
	private DataSource src;

	public boolean isLoggedIn() {
		return FacesContext.getCurrentInstance().getExternalContext()
				.getSessionMap().get("loginController") != null;
	}

	public String login() throws Exception, SQLException {
		Password pas = new Password();
		String hash;
		hash = pas.hash(getPassword());
		Connection connection;
		User user = new User();
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR,
				"Неверное имя пользователя или пароль!", "Length = 8");

		if (src == null)
			throw new SQLException("Can't create datasource");
		try {
			connection = src.getConnection();

			if (connection == null)
				throw new SQLException("Can't connect to database");

			PreparedStatement statement = connection
					.prepareStatement("SELECT * FROM user");

			ResultSet result = statement.executeQuery();

			while (result.next()) {
				user.setID(result.getLong("id"));
				user.setUsername(result.getString("username"));
				user.setPassword_hash(result.getString("password"));
			}

			connection.close();
			result.close();
		} catch (SQLException e) {
			FacesContext
					.getCurrentInstance()
					.addMessage(
							"reg:messages",
							new FacesMessage(
									FacesMessage.SEVERITY_FATAL,
									"Фатальная ошибка:",
									"Невозможно выполнить подключение к базе данных! Обратитесь к системному администратору."));
			return "login";
		}
		;

		if (user.getUsername().equals(name)
				&& user.getPassword_hash().equals(hash))
			FacesContext.getCurrentInstance().getExternalContext()
					.getSessionMap().put("loginController", this);
		else {
			FacesContext.getCurrentInstance().addMessage(
					"reg:messages",
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Ошибка:",
							"Неверный логин или пароль!"));
			return "login";
		}
		return "login";
	}

	public String logout() {
		if (!isLoggedIn())
			return "index";
		name = null;
		setPassword(null);

		HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
				.getExternalContext().getSession(false);
		session.invalidate();
		return "login";

		// here you wanna forward to your login page

	}
}

src/main/webapp/WEB-INF/templates/default.xhtml
<!--
    JBoss, Home of Professional Open Source
    Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>${artifactId}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</h:head>
<h:body>           
<p:layout fullPage="true">
    <p:layoutUnit position="west" resizable="true">
        West
    </p:layoutUnit>
 
    <p:layoutUnit position="center">
        <ui:insert name="content">
                    [Template content will be inserted here]
         </ui:insert>
    </p:layoutUnit>
</p:layout>
</h:body>
</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    JBoss, Home of Professional Open Source
    Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/mainLayout.html">
	
	 <ui:define name="sideBar">
    <ui:include src="sidemenu.xhtml"/>
  </ui:define>
 
	<ui:define name="content">
		<h1>Index Page</h1>
        
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam justo mi, malesuada in odio at, venenatis tempor risus. Morbi vitae eros porta, bibendum metus eget, auctor ex. Duis nec rhoncus odio, feugiat fringilla dolor. Sed ligula tortor, maximus in sem vel, laoreet iaculis tortor. Aliquam at augue a dolor aliquam euismod. Phasellus dignissim, lectus et placerat maximus, ex mi sodales nisl, nec porttitor nisl metus sed arcu. Maecenas rutrum eleifend sodales. Etiam egestas gravida ante ut interdum. Nullam ac neque urna. Nunc molestie eu lacus sed euismod. Phasellus interdum mi sapien, vitae mollis dolor tincidunt ac. Donec blandit quam ac enim lobortis faucibus. Curabitur finibus leo quis aliquam pellentesque.

In molestie euismod enim et tincidunt. Maecenas sed euismod felis. Vivamus rutrum, justo vel laoreet vehicula, neque leo pellentesque urna, sit amet commodo erat diam at nulla. Ut a molestie orci, ut blandit libero. Donec ultrices mi eu mauris blandit, id imperdiet ligula iaculis. Sed interdum ac lectus vel varius. Aliquam ac nisi vel ipsum cursus maximus. Maecenas ligula arcu, accumsan eu mollis vel, cursus at massa. Cras eleifend nisl sed sem pharetra porta.

Curabitur consectetur justo eu tortor convallis, sed venenatis augue feugiat. In hac habitasse platea dictumst. Fusce in sodales est, elementum tempus risus. Sed maximus pretium justo a hendrerit. Etiam scelerisque diam ac erat dapibus tristique. Fusce consectetur dui sed urna aliquet, eu auctor ante condimentum. Pellentesque egestas leo id molestie iaculis. Phasellus accumsan lacinia bibendum. Nulla ante nisl, malesuada non vestibulum at, finibus eu ipsum. Donec sed aliquam odio, a facilisis enim. Ut sagittis arcu nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus sapien urna, cursus interdum nibh non, pulvinar fermentum magna.

Nullam efficitur velit egestas tellus aliquam finibus. Nam tempor cursus congue. Vestibulum accumsan hendrerit lorem quis iaculis. Nam in elit congue, pulvinar turpis nec, viverra augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris a lobortis odio. Quisque lacus magna, fringilla id laoreet vitae, dictum eu felis. Mauris dignissim justo vitae urna porta ullamcorper. Sed eleifend lacus ac magna viverra, a vulputate ex iaculis. Integer pretium arcu sed orci rhoncus viverra.

Aliquam erat volutpat. Proin imperdiet risus nunc, quis mattis elit elementum non. Proin et leo gravida risus efficitur sollicitudin et malesuada tellus. Cras urna eros, commodo varius vestibulum at, mattis sed nibh. Duis vel ornare nibh. Praesent finibus mi pulvinar, sollicitudin arcu nec, fermentum ante. Aenean at quam vel justo vehicula pellentesque. Sed in mi nec dolor efficitur elementum. Suspendisse pulvinar scelerisque nunc, eu molestie tortor rutrum eu.

Donec aliquet ultricies congue. Pellentesque non velit at nulla scelerisque tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse et odio non arcu eleifend pellentesque. Aliquam id pretium tortor. Nulla leo ex, bibendum ac vestibulum vel, ultrices quis massa. Sed a mattis orci, eget consequat ante. Vivamus luctus leo sit amet consectetur posuere. Suspendisse finibus efficitur nisl, a dictum eros pretium id. Suspendisse eget ligula tincidunt, viverra enim sed, sollicitudin mi.

Vestibulum risus orci, pellentesque at nibh imperdiet, venenatis fermentum arcu. Maecenas sed dui placerat, dignissim risus ut, molestie elit. Aenean mattis nibh ut nunc imperdiet, sollicitudin volutpat magna lobortis. Vivamus aliquet dictum risus, quis sodales nisi iaculis in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum, felis eget efficitur molestie, velit felis rhoncus mi, et efficitur eros tellus ut leo. Mauris eget hendrerit lacus, vitae imperdiet lectus. Fusce condimentum, mauris accumsan finibus facilisis, massa odio gravida est, id volutpat libero nibh et urna.

Maecenas rutrum nibh sit amet dolor rhoncus, vitae aliquet nulla tincidunt. Vivamus sit amet nunc massa. Pellentesque interdum purus non erat porttitor ultricies id sit amet lacus. Nulla semper arcu arcu, id pretium lacus commodo sit amet. Mauris quis vehicula ante. Fusce varius non augue vel semper. Etiam iaculis venenatis nulla, ut venenatis mi pretium vel. Phasellus et odio pretium, hendrerit nisi quis, ornare nulla. Morbi euismod fringilla ipsum, fringilla aliquam mi ullamcorper non. In tempor magna ut enim efficitur, pharetra feugiat quam porttitor. Phasellus lacinia interdum dolor, et malesuada libero bibendum ut.

Quisque cursus lacus tortor, eget aliquet purus pellentesque sit amet. Phasellus convallis placerat urna eu lacinia. Integer consequat, est volutpat auctor convallis, neque neque mattis erat, placerat iaculis velit felis ac dui. Ut nec neque sapien. Pellentesque ut justo eget enim elementum rhoncus. Suspendisse porta nulla vestibulum, suscipit tellus in, mattis justo. Quisque dignissim et mauris in consequat. Sed elit mi, tincidunt id laoreet vitae, egestas vitae massa. Etiam nec faucibus nibh. Sed suscipit sapien dui, sit amet consectetur enim mollis id.

Ut aliquam maximus quam eu egestas. Nulla ac gravida tortor, quis sagittis orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque feugiat sapien id mauris auctor egestas. Praesent eleifend sapien augue, eget molestie turpis tincidunt vel. Maecenas egestas massa neque, in varius nisl porta eu. Aliquam id gravida risus. Integer non leo vitae tellus consectetur mollis in sit amet nulla. 

        
    </ui:define>
</ui:composition>

src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    
	<h:head>
		<title>Войти</title>
	</h:head> 
    <h:body>
		<h:form id="reg">
            <h2>Войти в систему</h2>
            <p:messages id="messages" showDetail="true" autoUpdate="true" />
            <h:panelGrid columns="3" columnClasses="titleCell" style=" width : 373px;">
                <h:outputLabel for="username" value="Имя пользователя (логин):" rendered="#{userController.loggedIn == false}" />
                <p:inputText id="username" value="#{userController.name}" restyle=" width : 143px;" rendered="#{userController.loggedIn == false}" />
                <h:message id="null" for="username" errorClass="invalid" />

                <h:outputLabel for="password" value="Пароль:" rendered="#{userController.loggedIn == false}" />
                <p:password id="password" value="#{userController.password}" style=" width : 143px;" rendered="#{userController.loggedIn == false}"/>
                <h:message id="null2" for="password" errorClass="invalid" />
            </h:panelGrid>

            <p>
                <h:panelGrid columns="2">
                    <p:commandButton id="register"
                        action="#{userController.login}"
                        ajax="false"
                        value="Войти" styleClass="login" rendered="#{userController.loggedIn == false}"
                         />
                    <p:commandButton actionListener="#{userController.logout}" value="Выйти" ajax="false"
                    	rendered="#{userController.loggedIn}"/>
                     
                </h:panelGrid>
            </p>
        </h:form>

        
    </h:body>
</html>

src/main/webapp/member.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    JBoss, Home of Professional Open Source
    Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    template="/WEB-INF/templates/default.xhtml">
    <ui:define name="content">
        <h1>Welcome to JBoss!</h1>

        <div>
            <p>You have successfully deployed a Java EE 6 Enterprise
                Application.</p>
            <h3>Your application can run on:</h3>
            <img src="resources/gfx/dualbrand_as7eap.png" />
        </div>

        <h:form id="reg">
            <h2>Member Registration</h2>
            <p>Enforces annotation-based constraints defined on the
                model class.</p>
            <h:panelGrid columns="3" columnClasses="titleCell">
                <h:outputLabel for="name" value="Name:" />
                <h:inputText id="name" value="#{newMember.name}" />
                <h:message for="name" errorClass="invalid" />

                <h:outputLabel for="email" value="Email:" />
                <h:inputText id="email" value="#{newMember.email}" />
                <h:message for="email" errorClass="invalid" />

                <h:outputLabel for="phoneNumber" value="Phone #:" />
                <h:inputText id="phoneNumber"
                    value="#{newMember.phoneNumber}" />
                <h:message for="phoneNumber" errorClass="invalid" />
            </h:panelGrid>

            <p>
                <h:panelGrid columns="2">
                    <h:commandButton id="register"
                        action="#{memberController.register}"
                        value="Register" styleClass="register" />
                    <h:messages styleClass="messages"
                        errorClass="invalid" infoClass="valid"
                        warnClass="warning" globalOnly="true" />
                </h:panelGrid>
            </p>
        </h:form>
        <h2>Members</h2>
        <h:panelGroup rendered="#{empty members}">
            <em>No registered members.</em>
        </h:panelGroup>
        <h:dataTable value="#{customer.getCustomerList()}" var="c"
    			styleClass="order-table"
    			headerClass="order-table-header"
    			rowClasses="order-table-odd-row,order-table-even-row"
    		>
 
    		<h:column>
    			<f:facet name="header">
    				Customer ID
    			</f:facet>
    				#{c.customerID}
    		</h:column>
 
    		<h:column>
    			<f:facet name="header">
    				Name
				</f:facet>
    				#{c.name}
    		</h:column>
 
 			<h:column>
    			<f:facet name="header">
    				Address
				</f:facet>
    				#{c.address}
    		</h:column>
 
    		<h:column>
    			<f:facet name="header">
    				Created Date
				</f:facet>
    				#{c.created_date}
    		</h:column>
 
    	</h:dataTable>
    </ui:define>
</ui:composition>

src/main/webapp/sidemenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
<body>
		   <p:menu style="width:100%; height:auto; margin:10px">
        <p:submenu label="Navigations">
            <p:menuitem value="External" url="http://www.primefaces.org" icon="ui-icon-home"/>
            <p:menuitem value="Internal" outcome="index" icon="ui-icon-star"/>
        </p:submenu>
    </p:menu>
    </body>
</ui:composition>

src/main/webapp/signup.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      template="/WEB-INF/templates/mainLayout.html"> 

<h:head></h:head> 

 
<ui:define name="content">
	<h:form id="register" style="width:985px; margin:0 auto">
	<p:messages id="messages" showDetail="false" autoUpdate="true"/>
		<p:panelGrid columns="3" styleClass="panelNoBorder">
			<h:outputLabel value="Имя пользователя" for="regName" />
			<p:inputText id="regName" value="Login" required="true" label="Имя пользователя" />
			<p:message for="regName" />
			
			<h:outputLabel value="Пароль" for="regPass1" />
			<p:password id="regPass1" label="Пароль" match="regPass2" required="true" value="Login" feedback="true" weakLabel="Слабый пароль"
                    goodLabel="Хороший пароль" strongLabel="Сильный пароль" promptLabel="Введите пароль" maxlength="60"/>
			<p:message for="regPass1" />
			
			<h:outputLabel value="Введите пароль снова" for="regPass2" />
			<p:password id="regPass2" label="Введите пароль снова" value="Login" required="true" />
			<p:message for="regPass2" />
			
			<p:captcha label="Капча" />
		</p:panelGrid>
		<p:commandButton value="Зарегистрировать" icon="ui-icon-check"/>
	</h:form>
</ui:define>
</ui:composition>